IF
	Clicked([ANYONE])
	InParty("Wulfg2")
THEN
	RESPONSE #100
		ActionOverride("Ulgarth",MoveBetweenAreas("RA5603",[2680.470],2))
		ActionOverride("Beogorn",MoveBetweenAreas("RA5603",[2682.470],2))
		ActionOverride("BarBar1",MoveBetweenAreas("RA5603",[2686.470],2))
		ActionOverride("BarBar2",MoveBetweenAreas("RA5603",[2680.472],2))
		ActionOverride("BarBar3",MoveBetweenAreas("RA5603",[2680.477],2))
		ActionOverride("BarBar4",MoveBetweenAreas("RA5603",[2680.474],2))
END


