IF
	Clicked([ANYONE])
	InParty("Wulfg2")
THEN
	RESPONSE #100
		ActionOverride("Ulgarth",MoveBetweenAreas("RA5603",[3450.2160],5))
		ActionOverride("Beogorn",MoveBetweenAreas("RA5603",[3450.2160],5))
		ActionOverride("BarBar1",MoveBetweenAreas("RA5603",[3450.2160],5))
		ActionOverride("BarBar2",MoveBetweenAreas("RA5603",[3450.2160],5))
		ActionOverride("BarBar3",MoveBetweenAreas("RA5603",[3450.2160],5))
		ActionOverride("BarBar4",MoveBetweenAreas("RA5603",[3450.2160],5))
END


