IF
	Global("Movetopone","LOCALS",0)
	CombatCounter(0)
	OR(6)
		Range(Player1,35)
		Range(Player2,35)
		Range(Player3,35)
		Range(Player4,35)
		Range(Player5,35)
		Range(Player6,35)
THEN
	RESPONSE #100
		MoveToObjectNoInterrupt(Player1)
		SetGlobal("Movetopone","LOCALS",1)
END

IF
	Global("Movetopone","LOCALS",1)
	Range(Player1,5)
THEN
	RESPONSE #100
		SetGlobal("Movetopone","LOCALS",2)
		SmallWait(1)
		StartDialogueNoSet(Player1)
END


