IF
	Global("Wulfgarsquest","GLOBAL",1)
	Global("IWDMovings","GLOBAL",0)
	Global("IWDMovings2","LOCALS",0)
	Delay(1)
THEN
	RESPONSE #100
		ChangeEnemyAlly(Myself,CONTROLLED)
		SetGlobal("IWDMovings2","LOCALS",1)
END

IF
	GlobalTimerExpired("Barbariannum1","GLOBAL")
	TimeOfDay(NIGHT)
	Global("Mespeaksenglish","LOCALS",0)
	CombatCounter(0)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@575066)
		SetGlobal("Mespeaksenglish","LOCALS",1)
		Continue()
END


