IF
	Delay(10)
	See(NearestEnemyOf(Myself))
	Global("Mushroom","LOCALS",0)
THEN
	RESPONSE #100
		IncrementGlobal("Mushroom","LOCALS",1)
		ForceSpellRES("ROT3402",Myself)       //SUMMON_MYCONID
END

IF
	Delay(20)
	See(NearestEnemyOf(Myself))
	GlobalLT("MushroomSummon","LOCALS",3)
THEN
	RESPONSE #100
		IncrementGlobal("MushroomSummon","LOCALS",1)
		ForceSpellRES("ROT3402",Myself)       //SUMMON_MYCONID
END


