IF
	Global("CreaWulfi","AR0602",0)
THEN
	RESPONSE #100
	SetGlobal("EntJar1","AR0602",2)
	SetGlobal("CreaWulfi","AR0602",1)
	CreateCreature("Wulfg2",[630.2340],13) 
END

IF
	Global("EntJar1","AR0602",0)
THEN
	RESPONSE #100
		ClearAllActions()
		SetGlobal("EntJar1","AR0602",1)
		HideGUI()
		StartCutSceneMode()
		StartCutScene("EntJar1")
		UnhideGUI()
END

IF
Global("EntJar1","AR0602",2)
PartyHasItem("Misc4b")
THEN
RESPONSE #100
SetGlobal("EntJar1","AR0602",0)
END


